[package]
name = "rust_jutsu"
version = "0.1.0"
edition = "2021"
authors = ["Dogigiri <m-moshtagh@pm.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
